### ISSUE TITLE
Remove redundante waiting tasks

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-collection-elasticstack#139]
In `tasks/elasticsearch-security.yml` we have several versions of tasks waiting for Elasticsearch to start.

I guess the following is redundant and can be removed.

```
- name: Check for open port tcp {{ elastic_elasticsearch_http_port }}
  wait_for:
    port: "{{ elastic_elasticsearch_http_port }}"
  tags:
    - certificates
    - renew_ca
    - renew_es_cert
```

I guess, when we remove it, we need to add the tags to the other waiting tasks. @afeefghannam89 you put a lot of effort in those tags, could you plese make sure we don't break anything and remove this task (if I'm right)
