### ISSUE TITLE
Enhancement : Add Variable for Version(s) which should be installed

### ISSUE THREAD

**Issue by frankhetterich** [NETWAYS/ansible-collection-elasticstack#175]
Currently the collection is always installing the latest versions of the elastic stack
But sometimes this is not wanted, for example when adding a new node to an existing ES Cluster without updating the whole cluster. 

It would be very useful to have the versions configurable via  variables

**Comment by frankhetterich** [comment]
Hello,
 thank you for pointing this out. The paragraph is unfortunately badly formatted, so we missed this variable. 
But this variable is defining the version for the whole stack. From our point of view it would be helpful to have such a variable for every software component. 
For example, the you can install a different version of a software component (e.g. because of a bug).

**Comment by martialblog** [comment]
Due to the way Ansible variables are scoped, this should be already possible. E.g.:

```
roles:
   - role: netways.elasticstack.kibana
     vars:
        elasticstack_version: 1.2.3
   - role: netways.elasticstack.logstash
     vars:
        elasticstack_version: 2.3.4
```
