### ISSUE TITLE
Suspected bug: "Enable Ingest Pipelines" task not working due to impossible redirect

### ISSUE THREAD

**Issue by Donien** [NETWAYS/ansible-collection-elasticstack#198]
Within **roles/beats/tasks/filebeat.yml** there is the following task:

```yaml
    - name: Enable Ingest Pipelines
      command: >
        /usr/bin/filebeat setup --pipelines &&
        /usr/bin/filebeat version > /etc/filebeat/{{ item }}_pipeline_created
      args:
        creates: "/etc/filebeat/{{ item }}_pipeline_created"
      with_items: "{{ beats_filebeat_modules }}"
      notify:
        - Restart Filebeat
      changed_when: false
```

It uses the `command` module. Within its shell command a redirect is used (`>`).
This leads to a problem: The redirect into the file does not work using the `command` module since no actual shell is used.  
It does however work using the `shell` module. We can even keep the `creates` argument, making this a pretty simple fix.
