### ISSUE TITLE
Logstash version number structure

### ISSUE THREAD

**Issue by psteinmetzcid** [NETWAYS/ansible-collection-elasticstack#205]
We added elasticstack_version to inventory as variable to all Hosts in the Cluster.
We have found that the Version number for Logstash in ubuntu is not the same as for all other products.

The Structure is e.g. '1:8.8.1-1' for Version 8.8.1.

I think it would be good to rebuild the task that compiles the version number for Logstash. This way, elasticstack_version does not have to be maintained multiple times in the playbook.

**Comment by martialblog** [comment]
Hi, thanks for the hint. We will look into this. 

Like you said, a workaround would be specify different scoped variables for the version:

```
roles:
   - role: netways.elasticstack.kibana
     vars:
        elasticstack_version: 1.2.3
   - role: netways.elasticstack.logstash
     vars:
        elasticstack_version: 2.3.4
```
