### ISSUE TITLE
enhancement: additional configuration for kibana.yml

### ISSUE THREAD

**Issue by psteinmetzcid** [NETWAYS/ansible-collection-elasticstack#208]
For my perspective it is a good enhancement to add the possibility to add additional parameters to the kibana.yml.

e.g. in our case the following parameters needed.
telemetry.enabled: false
monitoring.ui.ccs.enabled: false

I think a good approach are a generic way. 
For example have a variable like this and loop over it in the jinja template file

```
kibana.additional.parameter:
  telemetry.enabled: false
  monitoring.ui.ccs.enabled: false
  other_parameters: value
```
