### ISSUE TITLE
[Bug]: Extra fields in Filebeat inputs not working

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-collection-elasticstack#296]
### Please try to fill out as much of the information below as you can. Thank you!

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Describe the bug

When using die `fields` setting in `filebeat_log_inputs` you don't get the whole line in `fields` within `filebeat.yml`. Only the field name but not the value.

Thanks, @tbumke for reporting this bug.

### How to recreate the bug?

Use variables like this:

```
filebeat_log_inputs:
  messages:
    name: messages
    paths:
      - /var/log/messages
    fields:
      index_suffix: system
```
The value `system` will not be written to `filebeat.yml`.
