### ISSUE TITLE
[Bug]: beats_filebeat_syslog_udp_port and beats_filebeat_syslog_tcp_port have no impact

### ISSUE THREAD

**Issue by lcndsmr** [NETWAYS/ansible-collection-elasticstack#309]
### Please try to fill out as much of the information below as you can. Thank you!

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Describe the bug

The `beats_filebeat_syslog_udp_port` and `beats_filebeat_syslog_tcp_port` variables can be set, but have no impact, since they are not used in the `filebeat.yml.j2` template and the ports are hard-coded. 

Pull request to fix this will follow shortly

### How to recreate the bug?

Set up filebeat with the beats role and values in `beats_filebeat_syslog_udp_port: 5000` and `beats_filebeat_syslog_tcp_port: 5001`

Have a look in filebeat.yml.

Expectet result: 
```yaml
filebeat.inputs:
  - type: tcp
    enabled: true
    max_message_size: 10MiB
    host: "0.0.0.0:5000"
  - type: udp
    enabled: true
    max_message_size: 10MiB
    host: "0.0.0.0:5001"
```

actual behavior:
```yaml
filebeat.inputs:
  - type: tcp
    enabled: true
    max_message_size: 10MiB
    host: "0.0.0.0:514"
  - type: udp
    enabled: true
    max_message_size: 10MiB
    host: "0.0.0.0:514"
```
