### ISSUE TITLE
[Feature]: metricbeat oss > 7

### ISSUE THREAD

**Issue by cbeaujoin-stellar** [NETWAYS/ansible-collection-elasticstack#333]
### Describe the feature request

In the repo role, the following tasks seems to be wrong:
```
- name: Check for versions
  ansible.builtin.fail:
    msg: "No OSS versions later than 7 are available"
  when:
    - elasticstack_release | int > 7
    - elasticstack_variant == "oss"
```

Because there is an availlable version of metricbeats-oss version > 8
https://www.elastic.co/downloads/beats/metricbeat-oss/

So:
```
monitoring_elasticstack_release: 8
monitoring_elasticstack_version: 8.14.3
```
Should be allowed
